// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dc_templates.sql

package db

import (
	"context"
	"database/sql"
)

const CheckTemplateHasDCs = `-- name: CheckTemplateHasDCs :one
SELECT COUNT(*)
FROM delivery_challans
WHERE template_id = ?
`

func (q *Queries) CheckTemplateHasDCs(ctx context.Context, templateID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CheckTemplateHasDCs, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CheckTemplateNameUnique = `-- name: CheckTemplateNameUnique :one
SELECT COUNT(*)
FROM dc_templates
WHERE project_id = ? AND name = ?
`

type CheckTemplateNameUniqueParams struct {
	ProjectID int64
	Name      string
}

func (q *Queries) CheckTemplateNameUnique(ctx context.Context, arg CheckTemplateNameUniqueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CheckTemplateNameUnique, arg.ProjectID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CheckTemplateNameUniqueExcludeID = `-- name: CheckTemplateNameUniqueExcludeID :one
SELECT COUNT(*)
FROM dc_templates
WHERE project_id = ? AND name = ? AND id != ?
`

type CheckTemplateNameUniqueExcludeIDParams struct {
	ProjectID int64
	Name      string
	ID        int64
}

func (q *Queries) CheckTemplateNameUniqueExcludeID(ctx context.Context, arg CheckTemplateNameUniqueExcludeIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CheckTemplateNameUniqueExcludeID, arg.ProjectID, arg.Name, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateTemplate = `-- name: CreateTemplate :execresult
INSERT INTO dc_templates (project_id, name, purpose)
VALUES (?, ?, ?)
`

type CreateTemplateParams struct {
	ProjectID int64
	Name      string
	Purpose   string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateTemplate, arg.ProjectID, arg.Name, arg.Purpose)
}

const DeleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM dc_templates
WHERE id = ? AND project_id = ?
`

type DeleteTemplateParams struct {
	ID        int64
	ProjectID int64
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.ExecContext(ctx, DeleteTemplate, arg.ID, arg.ProjectID)
	return err
}

const DeleteTemplateProducts = `-- name: DeleteTemplateProducts :exec
DELETE FROM dc_template_products
WHERE template_id = ?
`

func (q *Queries) DeleteTemplateProducts(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTemplateProducts, templateID)
	return err
}

const GetTemplateByID = `-- name: GetTemplateByID :one
SELECT
    t.id, t.project_id, t.name, t.purpose, t.created_at, t.updated_at,
    COUNT(DISTINCT tp.product_id) AS product_count,
    COUNT(DISTINCT CASE WHEN dc.dc_type = 'transit' THEN dc.id END) AS transit_count,
    COUNT(DISTINCT CASE WHEN dc.dc_type = 'official' THEN dc.id END) AS official_count,
    COUNT(DISTINCT dc.id) AS usage_count
FROM dc_templates t
LEFT JOIN dc_template_products tp ON t.id = tp.template_id
LEFT JOIN delivery_challans dc ON t.id = dc.template_id
WHERE t.id = ?
GROUP BY t.id
`

type GetTemplateByIDRow struct {
	ID            int64
	ProjectID     int64
	Name          string
	Purpose       string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	ProductCount  int64
	TransitCount  int64
	OfficialCount int64
	UsageCount    int64
}

func (q *Queries) GetTemplateByID(ctx context.Context, id int64) (GetTemplateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetTemplateByID, id)
	var i GetTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Purpose,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductCount,
		&i.TransitCount,
		&i.OfficialCount,
		&i.UsageCount,
	)
	return i, err
}

const GetTemplateDuplicateSource = `-- name: GetTemplateDuplicateSource :many
SELECT product_id, default_quantity, sort_order
FROM dc_template_products
WHERE template_id = ?
ORDER BY sort_order
`

type GetTemplateDuplicateSourceRow struct {
	ProductID       int64
	DefaultQuantity sql.NullInt64
	SortOrder       sql.NullInt64
}

func (q *Queries) GetTemplateDuplicateSource(ctx context.Context, templateID int64) ([]GetTemplateDuplicateSourceRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTemplateDuplicateSource, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplateDuplicateSourceRow{}
	for rows.Next() {
		var i GetTemplateDuplicateSourceRow
		if err := rows.Scan(&i.ProductID, &i.DefaultQuantity, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTemplateProductIDs = `-- name: GetTemplateProductIDs :many
SELECT product_id, default_quantity
FROM dc_template_products
WHERE template_id = ?
`

type GetTemplateProductIDsRow struct {
	ProductID       int64
	DefaultQuantity sql.NullInt64
}

func (q *Queries) GetTemplateProductIDs(ctx context.Context, templateID int64) ([]GetTemplateProductIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTemplateProductIDs, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplateProductIDsRow{}
	for rows.Next() {
		var i GetTemplateProductIDsRow
		if err := rows.Scan(&i.ProductID, &i.DefaultQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTemplateProducts = `-- name: GetTemplateProducts :many
SELECT
    p.id, p.project_id, p.item_name, p.item_description, p.hsn_code, p.uom,
    p.brand_model, p.per_unit_price, p.gst_percentage, p.created_at, p.updated_at,
    tp.default_quantity
FROM products p
INNER JOIN dc_template_products tp ON p.id = tp.product_id
WHERE tp.template_id = ?
ORDER BY tp.sort_order, p.item_name
`

type GetTemplateProductsRow struct {
	ID              int64
	ProjectID       int64
	ItemName        string
	ItemDescription string
	HsnCode         sql.NullString
	Uom             sql.NullString
	BrandModel      string
	PerUnitPrice    sql.NullFloat64
	GstPercentage   sql.NullFloat64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DefaultQuantity sql.NullInt64
}

func (q *Queries) GetTemplateProducts(ctx context.Context, templateID int64) ([]GetTemplateProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTemplateProducts, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplateProductsRow{}
	for rows.Next() {
		var i GetTemplateProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemName,
			&i.ItemDescription,
			&i.HsnCode,
			&i.Uom,
			&i.BrandModel,
			&i.PerUnitPrice,
			&i.GstPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTemplatesByProjectID = `-- name: GetTemplatesByProjectID :many
SELECT
    t.id, t.project_id, t.name, t.purpose, t.created_at, t.updated_at,
    COUNT(DISTINCT tp.product_id) AS product_count,
    COUNT(DISTINCT CASE WHEN dc.dc_type = 'transit' THEN dc.id END) AS transit_count,
    COUNT(DISTINCT CASE WHEN dc.dc_type = 'official' THEN dc.id END) AS official_count,
    COUNT(DISTINCT dc.id) AS usage_count
FROM dc_templates t
LEFT JOIN dc_template_products tp ON t.id = tp.template_id
LEFT JOIN delivery_challans dc ON t.id = dc.template_id
WHERE t.project_id = ?
GROUP BY t.id
ORDER BY t.created_at DESC
`

type GetTemplatesByProjectIDRow struct {
	ID            int64
	ProjectID     int64
	Name          string
	Purpose       string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	ProductCount  int64
	TransitCount  int64
	OfficialCount int64
	UsageCount    int64
}

func (q *Queries) GetTemplatesByProjectID(ctx context.Context, projectID int64) ([]GetTemplatesByProjectIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTemplatesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplatesByProjectIDRow{}
	for rows.Next() {
		var i GetTemplatesByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Purpose,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
			&i.TransitCount,
			&i.OfficialCount,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertTemplateProduct = `-- name: InsertTemplateProduct :exec
INSERT INTO dc_template_products (template_id, product_id, default_quantity, sort_order)
VALUES (?, ?, ?, ?)
`

type InsertTemplateProductParams struct {
	TemplateID      int64
	ProductID       int64
	DefaultQuantity sql.NullInt64
	SortOrder       sql.NullInt64
}

func (q *Queries) InsertTemplateProduct(ctx context.Context, arg InsertTemplateProductParams) error {
	_, err := q.db.ExecContext(ctx, InsertTemplateProduct,
		arg.TemplateID,
		arg.ProductID,
		arg.DefaultQuantity,
		arg.SortOrder,
	)
	return err
}

const UpdateTemplate = `-- name: UpdateTemplate :exec
UPDATE dc_templates
SET name = ?, purpose = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND project_id = ?
`

type UpdateTemplateParams struct {
	Name      string
	Purpose   string
	ID        int64
	ProjectID int64
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTemplate,
		arg.Name,
		arg.Purpose,
		arg.ID,
		arg.ProjectID,
	)
	return err
}
